<script lang="ts">
  import { goto } from '$app/navigation';
  import SiteHeader from '$lib/SiteHeader.svelte';
  let query = '';
  function search() { goto(`/explore${query.trim() ? `?q=${encodeURIComponent(query.trim())}` : ''}`); }
</script>
<svelte:head>
  <title>NZ Records — Explore New Zealand Public Records & Connections</title>
  <meta name="description" content="Explore New Zealand public records and connections between people, companies, charities and organisations. Every connection links back to its source." />
  <link rel="canonical" href="https://nzrecords.co.nz/" />
  <meta property="og:site_name" content="NZ Records" />
  <meta property="og:title" content="NZ Records — Explore New Zealand Public Records & Connections" />
  <meta property="og:description" content="Explore New Zealand public records and connections between people, companies, charities and organisations. Every connection links back to its source." />
  <meta property="og:url" content="https://nzrecords.co.nz/" />
</svelte:head>
<SiteHeader />
<main>
<section class="hero"><p class="kicker">New Zealand public records</p><h1>Find people and organisations.<br/>See how they are connected.</h1><p class="lede">NZ Records brings public information together in one place. Search a record, follow its connections, and check the original source.</p>
<form class="search" on:submit|preventDefault={search}><label for="home-search">Search public records</label><div><input id="home-search" bind:value={query} placeholder="Name, organisation or NZBN"/><button type="submit">Search</button></div></form>
</section>
<section class="browse"><h2>Browse public records</h2><div class="links"><a href="/directory?kind=charities&letter=A"><strong>Charities</strong><span>Browse charity records alphabetically</span><b>Browse charities →</b></a><a href="/directory?kind=officers&letter=A"><strong>Charity officer records</strong><span>Browse people and organisations listed as charity officers</span><b>Browse officer records →</b></a></div></section>
<section class="about" id="about"><h2>About NZ Records</h2><div><p>NZ Records helps people explore relationships found in New Zealand public records. It shows what the source data says without deciding what a connection means.</p><p>Every relationship is linked to its evidence so you can check the source yourself.</p></div></section>
</main><footer><div><strong>NZ Records</strong><span>Follow the connections. Check the evidence. · Open-source civic technology.</span></div></footer>
<style>:global(*){box-sizing:border-box}:global(body){margin:0;background:#f7f7f4;color:#202624;font-family:Arial,Helvetica,sans-serif}:global(a){color:#135f50}main{max-width:1120px;margin:auto;padding:0 28px}.hero{padding:72px 0 68px;max-width:850px}.kicker{font-size:15px;font-weight:700;color:#176b5a;margin:0 0 15px}.hero h1{font-family:Georgia,'Times New Roman',serif;font-size:clamp(42px,6vw,66px);line-height:1.08;letter-spacing:-.025em;margin:0}.lede{font-size:20px;line-height:1.55;max-width:760px;color:#4f5955;margin:27px 0 35px}.search{max-width:760px}.search label{display:block;font-size:15px;font-weight:700;margin-bottom:9px}.search div{display:flex}.search input{min-width:0;flex:1;border:2px solid #5c6662;border-right:0;background:#fff;border-radius:3px 0 0 3px;padding:15px;font-size:17px;color:#202624}.search input:focus{outline:3px solid #f1c84c;outline-offset:0}.search button{border:0;background:#176b5a;color:white;padding:0 28px;font-size:16px;font-weight:700;border-radius:0 3px 3px 0;cursor:pointer}.search button:hover{background:#105245}.browse,.about{border-top:1px solid #cfd4d0;padding:42px 0 50px}.browse h2,.about h2{font-family:Georgia,'Times New Roman',serif;font-size:30px;margin:0 0 24px}.links{display:grid;grid-template-columns:1fr 1fr;gap:20px}.links a{background:#fff;border:1px solid #cfd4d0;border-top:4px solid #176b5a;padding:24px;text-decoration:none;display:flex;flex-direction:column;align-items:flex-start;gap:9px}.links a:hover strong,.links a:hover b{text-decoration:underline}.links strong{font-family:Georgia,'Times New Roman',serif;font-size:23px;color:#202624}.links span{color:#59635f;line-height:1.5}.links b{font-size:14px;margin-top:8px}.about{display:grid;grid-template-columns:300px 1fr;gap:50px}.about p{font-size:17px;line-height:1.65;margin:0 0 15px;color:#46504c}footer{background:#e8ebe8;border-top:1px solid #cbd0cc;margin-top:40px}footer>div{max-width:1120px;margin:auto;padding:30px 28px;display:flex;justify-content:space-between;gap:20px;font-size:13px;color:#58615d}footer strong{color:#202624}@media(max-width:700px){.hero{padding-top:48px}.hero h1{font-size:42px}.search div{flex-direction:column}.search input{border:2px solid #5c6662;border-radius:3px}.search button{padding:14px;border-radius:3px;margin-top:8px}.links,.about{grid-template-columns:1fr}.about{gap:5px}footer>div{flex-direction:column}}</style>