<script lang="ts">
  import { goto } from '$app/navigation';
  let query = '';
  function search() { goto(`/explore${query.trim() ? `?q=${encodeURIComponent(query.trim())}` : ''}`); }
</script>
<svelte:head><title>NZ Connections</title></svelte:head>
<header class="topbar"><a class="brand" href="/">NZ <span>Connections</span></a><nav><a href="/explore">Search</a><a href="/directory?kind=charities&letter=A">Charities</a><a href="/directory?kind=officers&letter=A">Charity Officers</a><a href="#about">About</a></nav></header>
<main>
<section class="hero"><div class="eyebrow">PUBLIC RECORDS · CONNECTED</div><h1>Follow the connections.<br/><em>Check the evidence.</em></h1><p class="lede">Explore relationships between New Zealand companies, people, public agencies and government contracts. Every connection points back to its source.</p>
<form class="search" on:submit|preventDefault={search}><span>⌕</span><input bind:value={query} aria-label="Search" placeholder="Search public records…"/><button type="submit">Explore</button></form>
<div class="directories"><a href="/directory?kind=charities&letter=A"><b>Charities</b><span>Browse imported charities A–Z →</span></a><a href="/directory?kind=officers&letter=A"><b>Charity Officers</b><span>Browse public officer records A–Z →</span></a></div>
</section>
<section class="principles" id="about"><article><strong>01</strong><h2>Evidence, not accusations</h2><p>NZ Connections presents public records and their relationships. It does not decide what those relationships mean.</p></article><article><strong>02</strong><h2>Source everything</h2><p>Relationships carry provenance: dataset, source record, publication date and retrieval date.</p></article><article><strong>03</strong><h2>Explore the network</h2><p>Move from an organisation to its officers and other connected public records.</p></article></section>
</main><footer><span>NZ Connections · Open-source civic technology</span><span>Facts should be traceable.</span></footer>
<style>:global(*){box-sizing:border-box}:global(body){margin:0;background:#07110f;color:#edf5f1;font-family:Inter,system-ui,sans-serif}:global(a){color:inherit;text-decoration:none}.topbar{height:74px;display:flex;align-items:center;justify-content:space-between;padding:0 max(24px,6vw);border-bottom:1px solid #1c302b;background:#07110fe8;position:sticky;top:0;z-index:10}.brand{font-weight:850;font-size:20px}.brand span{color:#4de1a1}.topbar nav{display:flex;gap:24px;color:#9db0aa;font-size:13px}.topbar nav a:hover{color:#edf5f1}main{max-width:1220px;margin:auto;padding:0 28px}.hero{padding:110px 0 100px;max-width:920px}.eyebrow{font-size:12px;letter-spacing:.18em;font-weight:800;color:#4de1a1;margin-bottom:22px}.hero h1{font-size:clamp(48px,7.2vw,88px);line-height:.98;letter-spacing:-.055em;margin:0;font-weight:820}.hero h1 em{font-style:normal;color:#91a49e}.lede{font-size:20px;line-height:1.6;color:#aabbb5;max-width:760px;margin:34px 0}.search{display:flex;align-items:center;gap:12px;background:#0e1d19;border:1px solid #29463d;border-radius:14px;padding:8px 8px 8px 18px;max-width:760px;box-shadow:0 18px 50px #0005}.search span{font-size:28px;color:#5f766e}.search input{flex:1;min-width:0;background:transparent;border:0;outline:0;color:#f4faf7;font-size:17px;padding:14px 4px}.search button{border:0;border-radius:9px;background:#4de1a1;color:#06100d;font-weight:800;padding:15px 24px;cursor:pointer}.directories{display:grid;grid-template-columns:1fr 1fr;gap:12px;max-width:760px;margin-top:18px}.directories a{border:1px solid #29443b;background:#0b1814;border-radius:11px;padding:17px 18px;display:flex;flex-direction:column;gap:5px}.directories a:hover{border-color:#4de1a1;background:#0e211a}.directories b{font-size:14px}.directories span{font-size:11px;color:#71867e}.principles{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #20332d;border-bottom:1px solid #20332d}.principles article{padding:42px 34px 46px 0}.principles article+article{border-left:1px solid #20332d;padding-left:34px}.principles strong{font-size:11px;color:#4de1a1}.principles h2{font-size:19px}.principles p{color:#829790;line-height:1.65;font-size:14px}footer{max-width:1220px;margin:auto;padding:28px;display:flex;justify-content:space-between;border-top:1px solid #20332d;color:#62766f;font-size:12px}@media(max-width:760px){.topbar nav{display:none}.hero{padding:72px 0}.directories,.principles{grid-template-columns:1fr}.principles article,.principles article+article{padding:28px 0;border-left:0;border-top:1px solid #20332d}.principles article:first-child{border-top:0}footer{flex-direction:column;gap:8px}}</style>