<script lang="ts">
  import { page } from '$app/state';
  import { afterNavigate, goto } from '$app/navigation';
  import SiteHeader from '$lib/SiteHeader.svelte';

  type SearchResult = { id: string | number; canonical_name?: string; name?: string; entity_type?: string; type?: string; public_type?: string; tender_outcome?: string | null; rfx_id?: string | null; supplier_rfx_id?: string | null; nzbn?: string | null; company_number?: string | null; status?: string | null; relationship_count?: number };
  function displayType(entity: SearchResult) { if (entity.public_type) return entity.public_type; const raw = entity.entity_type ?? entity.type ?? 'Public record'; if (raw === 'public_agency') return 'Government agency'; if (raw === 'contract') return 'Government tender'; if (raw === 'other') return 'Public record'; return raw.replace('_', ' '); }
  function displayName(entity: SearchResult) { const name = entity.canonical_name ?? entity.name ?? 'Unnamed record'; if (entity.public_type === 'Government tender' && entity.rfx_id) return name.replace(new RegExp(`^Procurement record RFx ${entity.rfx_id} — `), ''); if (entity.public_type === 'GETS supplier record') return name.replace(/^Supplier record — /, '').replace(/ — RFx .*$/, ''); return name; }
  const pageSize = 25;
  function readQueryFromUrl() { return page.url.searchParams.get('q') ?? ''; }
  function readPageFromUrl() { return Math.max(1, Number(page.url.searchParams.get('page') ?? 1) || 1); }
  let query = $state(readQueryFromUrl());
  let pageNum = $state(readPageFromUrl());
  let results = $state<SearchResult[]>([]);
  let loading = $state(false);
  let total = $state(0);
  let totalPages = $state(1);
  let searchError = $state<string | null>(null);
  let timer: ReturnType<typeof setTimeout>;
  function buildUrl(nextPage = pageNum) { const url = new URL(page.url); url.search = ''; if (query.trim()) url.searchParams.set('q', query.trim()); if (nextPage > 1) url.searchParams.set('page', String(nextPage)); return `${url.pathname}${url.search}`; }
  async function runSearchFor(q: string, nextPage: number) { const targetPage = Math.max(1, nextPage); pageNum = targetPage; searchError = null; if (q.length < 2) { results = []; total = 0; totalPages = 1; return; } loading = true; try { const params = new URLSearchParams({ q, page: String(targetPage), pageSize: String(pageSize) }); const response = await fetch(`/api/search?${params.toString()}`); if (!response.ok) { searchError = 'SEARCH_ERROR'; results = []; total = 0; totalPages = 1; return; } const payload = await response.json(); const liveResults = Array.isArray(payload.results) ? payload.results : []; const liveTotalPages = Math.max(1, Number(payload.totalPages ?? 1)); results = liveResults; total = Number(payload.total ?? liveResults.length); totalPages = liveTotalPages; pageNum = Math.max(1, Math.min(Number(payload.page ?? targetPage), liveTotalPages)); } catch { searchError = 'SEARCH_ERROR'; results = []; total = 0; totalPages = 1; } finally { loading = false; } }
  function syncQuery() { clearTimeout(timer); timer = setTimeout(() => { pageNum = 1; goto(buildUrl(1), { replaceState: true, noScroll: true, keepFocus: true }); runSearchFor(query.trim(), 1); }, 180); }
  function goToPage(nextPage: number) { pageNum = Math.max(1, Math.min(nextPage, totalPages)); goto(buildUrl(pageNum), { replaceState: false, noScroll: true }); }
  function pages() { const start = Math.max(1, pageNum - 2); const end = Math.min(totalPages, pageNum + 2); return Array.from({ length: end - start + 1 }, (_, index) => start + index); }
  function summaryText() { if (loading) return 'Searching…'; if (searchError) return 'Search failed'; if (!query.trim() || query.trim().length < 2) return 'Enter at least two characters to search records'; if (total === 0) return 'No records found'; const start = (pageNum - 1) * pageSize + 1; const end = Math.min(pageNum * pageSize, total); return `Showing ${start.toLocaleString()}–${end.toLocaleString()} of ${total.toLocaleString()} results`; }
  async function syncFromUrl() { if (page.url.pathname !== '/explore') return; const nextQuery = readQueryFromUrl(); const nextPage = readPageFromUrl(); query = nextQuery; await runSearchFor(nextQuery.trim(), nextPage); }
  afterNavigate(() => { syncFromUrl(); });
</script>
<svelte:head><title>Search · NZ Records</title><meta name="description" content="Search New Zealand public records by name, organisation or NZBN and follow source-backed connections." /></svelte:head>
<SiteHeader />
<main><p class="breadcrumb"><a href="/">Home</a> / Search</p><h1>Search public records</h1><p class="intro">Search names, organisations and identifiers in the NZ Records database.</p><label class="search"><span>Search</span><div><input bind:value={query} oninput={syncQuery} placeholder="Name, organisation or NZBN"/><button onclick={() => { pageNum = 1; goto(buildUrl(1), { replaceState: true, noScroll: true }); runSearchFor(query.trim(), 1); }}>Search</button></div></label>
<div class="summary">{summaryText()}</div>{#if searchError}<div class="error" role="alert">Search is temporarily unavailable. Please try again.</div>{/if}<section>{#each results as entity}{@const id=entity.id}{@const name=displayName(entity)}{@const type=displayType(entity)}{@const subtitle=[type,entity.tender_outcome,entity.rfx_id?`RFx number ${entity.rfx_id}`:entity.supplier_rfx_id?`RFx number ${entity.supplier_rfx_id}`:null,entity.status,entity.nzbn?`NZBN ${entity.nzbn}`:null].filter(Boolean).join(' · ')}{@const connections=Number(entity.relationship_count??0)}<a class="result" href={`/record/${id}`}><div><strong>{name}</strong><span>{subtitle}</span></div><div class="connections"><b>{connections}</b><span>{connections===1?'connection':'connections'}</span></div><span class="view">View record</span></a>{/each}{#if !loading&&results.length===0&&query.trim().length>=2&&!searchError}<div class="empty">No records match your search.</div>{/if}</section>
{#if totalPages > 1}<nav class="pagination" aria-label="Pagination"><button disabled={pageNum === 1 || loading} onclick={() => goToPage(pageNum - 1)}>Previous</button>{#if pages()[0] > 1}<button onclick={() => goToPage(1)}>1</button>{#if pages()[0] > 2}<span>…</span>{/if}{/if}{#each pages() as p}<button class:active={p === pageNum} aria-current={p === pageNum ? 'page' : undefined} onclick={() => goToPage(p)}>{p}</button>{/each}{#if pages()[pages().length - 1] < totalPages}{#if pages()[pages().length - 1] < totalPages - 1}<span>…</span>{/if}<button onclick={() => goToPage(totalPages)}>{totalPages}</button>{/if}<button disabled={pageNum === totalPages || loading} onclick={() => goToPage(pageNum + 1)}>Next</button></nav>{/if}</main>
<style>:global(*){box-sizing:border-box}:global(body){margin:0;background:#f7f7f4;color:#202624;font-family:Arial,Helvetica,sans-serif}:global(a){color:#135f50}main{max-width:960px;margin:auto;padding:38px 28px 90px}.breadcrumb{font-size:13px;color:#68726e;margin:0 0 30px}.breadcrumb a{text-decoration:underline}h1{font-family:Georgia,'Times New Roman',serif;font-size:46px;margin:0 0 10px;letter-spacing:-.02em}.intro{font-size:18px;color:#58625e;margin:0 0 30px}.search{display:block;max-width:760px}.search>span{display:block;font-size:15px;font-weight:700;margin-bottom:8px}.search div{display:flex}.search input{flex:1;min-width:0;border:2px solid #5c6662;border-right:0;background:#fff;padding:14px;font-size:16px;border-radius:3px 0 0 3px}.search input:focus{outline:3px solid #f1c84c}.search button{border:0;background:#176b5a;color:#fff;font-size:15px;font-weight:700;padding:0 25px;cursor:pointer;border-radius:0 3px 3px 0}.summary{display:flex;justify-content:space-between;align-items:center;margin-top:35px;border-bottom:2px solid #69736e;padding-bottom:11px;font-size:14px;font-weight:700}.error{margin-top:16px;border-left:5px solid #9f3a38;background:#fff1f0;color:#5b201f;padding:14px 16px;font-weight:700}section{background:#fff}.result{display:grid;grid-template-columns:1fr 100px 100px;gap:20px;align-items:center;padding:19px 15px;border-bottom:1px solid #d5dad6;color:#202624;text-decoration:none}.result:hover{background:#f1f4f1}.result>div:first-child{display:flex;flex-direction:column;gap:5px}.result strong{font-size:17px;color:#135f50;text-decoration:underline}.result div>span{font-size:13px;color:#68726e}.connections{display:flex;flex-direction:column}.connections b{font-size:20px}.view{font-weight:700;color:#135f50}.empty{padding:28px;background:#fff;color:#69726e}.pagination{display:flex;justify-content:center;align-items:center;gap:6px;flex-wrap:wrap;margin-top:24px}.pagination button{min-width:38px;border:1px solid #bfc6c1;background:#fff;color:#135f50;font-weight:700;padding:9px 11px;border-radius:3px;cursor:pointer}.pagination button.active{background:#176b5a;color:#fff}.pagination button:disabled{opacity:.45;cursor:not-allowed}@media(max-width:700px){.result{grid-template-columns:1fr}.connections{flex-direction:row;gap:5px}.search div{flex-direction:column}.search input{border-right:2px solid #5c6662;border-radius:3px 3px 0 0}.search button{min-height:46px;border-radius:0 0 3px 3px}}</style>
