<script lang="ts">
 import {page} from '$app/state'; import {goto} from '$app/navigation'; import {findDemoEntities} from '$lib/demo';
 type SearchResult={id:string|number;canonical_name?:string;name?:string;entity_type?:string;type?:string;nzbn?:string|null;company_number?:string|null;status?:string|null;subtitle?:string;relationship_count?:number};
 let query=$state(page.url.searchParams.get('q')??'');let results=$state<SearchResult[]>(findDemoEntities(query));let mode=$state<'demo'|'live'>('demo');let loading=$state(false);let timer:ReturnType<typeof setTimeout>;
 async function runSearch(){const q=query.trim();if(q.length<2){results=findDemoEntities(q);mode='demo';return;}loading=true;try{const response=await fetch(`/api/search?q=${encodeURIComponent(q)}`);if(response.ok){const payload=await response.json();if(Array.isArray(payload.results)){results=payload.results;mode='live';return;}}results=findDemoEntities(q);mode='demo';}catch{results=findDemoEntities(q);mode='demo';}finally{loading=false;}}
 function syncQuery(){clearTimeout(timer);timer=setTimeout(()=>{const url=new URL(page.url);if(query.trim())url.searchParams.set('q',query.trim());else url.searchParams.delete('q');goto(`${url.pathname}${url.search}`,{replaceState:true,noScroll:true,keepFocus:true});runSearch();},180);}$effect(()=>{runSearch();});
</script>
<svelte:head><title>Search · NZ Records</title><meta name="description" content="Search New Zealand public records by name, organisation or NZBN and follow source-backed connections." /></svelte:head>
<header><div><a class="brand" href="/">NZ Records</a><nav><a href="/explore">Search</a><a href="/directory?kind=charities&letter=A">Charities</a><a href="/directory?kind=officers&letter=A">Officer records</a></nav></div></header>
<main><p class="breadcrumb"><a href="/">Home</a> / Search</p><h1>Search public records</h1><p class="intro">Search names, organisations and identifiers in the NZ Records database.</p><label class="search"><span>Search</span><div><input bind:value={query} oninput={syncQuery} autofocus placeholder="Name, organisation or NZBN"/><button onclick={runSearch}>Search</button></div></label>
<div class="summary">{loading?'Searching…':`${results.length} ${results.length===1?'record':'records'} found`}{#if mode==='demo'}<span>Demo data</span>{/if}</div><section>{#each results as entity}{@const id=entity.id}{@const name=entity.canonical_name??entity.name??'Unnamed record'}{@const type=entity.entity_type??entity.type??'other'}{@const subtitle=entity.subtitle??[type.replace('_',' '),entity.status,entity.nzbn?`NZBN ${entity.nzbn}`:null].filter(Boolean).join(' · ')}{@const connections=Number(entity.relationship_count??0)}<a class="result" href={mode==='demo'?`/entity/${id}`:`/record/${id}`}><div><strong>{name}</strong><span>{subtitle}</span></div>{#if mode==='live'}<div class="connections"><b>{connections}</b><span>{connections===1?'connection':'connections'}</span></div>{/if}<span class="view">View record</span></a>{/each}{#if !loading&&results.length===0}<div class="empty">No records match your search.</div>{/if}</section>
{#if mode==='demo'}<p class="demo">The fictional demo records are shown only when live results are not available.</p>{/if}</main>
<style>:global(*){box-sizing:border-box}:global(body){margin:0;background:#f7f7f4;color:#202624;font-family:Arial,Helvetica,sans-serif}:global(a){color:#135f50}header{background:#fff;border-top:5px solid #176b5a;border-bottom:1px solid #d9ddd9}header>div{max-width:960px;margin:auto;padding:19px 28px;display:flex;justify-content:space-between;align-items:center}.brand{font-size:22px;font-weight:700;color:#202624;text-decoration:none}header nav{display:flex;gap:24px}header nav a{font-size:14px;font-weight:600}main{max-width:960px;margin:auto;padding:38px 28px 90px}.breadcrumb{font-size:13px;color:#68726e;margin:0 0 30px}.breadcrumb a{text-decoration:underline}h1{font-family:Georgia,'Times New Roman',serif;font-size:46px;margin:0 0 10px;letter-spacing:-.02em}.intro{font-size:18px;color:#58625e;margin:0 0 30px}.search{display:block;max-width:760px}.search>span{display:block;font-size:15px;font-weight:700;margin-bottom:8px}.search div{display:flex}.search input{flex:1;min-width:0;border:2px solid #5c6662;border-right:0;background:#fff;padding:14px;font-size:16px;border-radius:3px 0 0 3px}.search input:focus{outline:3px solid #f1c84c}.search button{border:0;background:#176b5a;color:#fff;font-size:15px;font-weight:700;padding:0 25px;cursor:pointer;border-radius:0 3px 3px 0}.summary{display:flex;justify-content:space-between;align-items:center;margin-top:35px;border-bottom:2px solid #69736e;padding-bottom:11px;font-size:14px;font-weight:700}.summary span{font-size:12px;background:#f4e9b8;padding:5px 8px}section{background:#fff}.result{display:grid;grid-template-columns:1fr 100px 100px;gap:20px;align-items:center;padding:19px 15px;border-bottom:1px solid #d5dad6;color:#202624;text-decoration:none}.result:hover{background:#f1f4f1}.result>div:first-child{display:flex;flex-direction:column;gap:5px}.result strong{font-size:17px;color:#135f50;text-decoration:underline}.result div>span{font-size:13px;color:#68726e}.connections{display:flex;flex-direction:column}.connections b{font-size:17px}.connections span{font-size:11px}.view{font-size:13px;color:#135f50;text-decoration:underline}.empty{padding:35px 15px;color:#68726e}.demo{font-size:12px;color:#68726e;margin-top:18px}@media(max-width:650px){header>div{align-items:flex-start;flex-direction:column;gap:15px}header nav{flex-wrap:wrap;gap:12px 18px}h1{font-size:38px}.result{grid-template-columns:1fr auto}.view{display:none}.search div{flex-direction:column}.search input{border:2px solid #5c6662;border-radius:3px}.search button{padding:13px;margin-top:7px;border-radius:3px}}</style>