<script lang="ts">
  import { page } from '$app/state';
  import { goto } from '$app/navigation';
  const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
  let kind = $state(page.url.searchParams.get('kind') === 'officers' ? 'officers' : 'charities');
  let letter = $state((page.url.searchParams.get('letter') ?? 'A').toUpperCase());
  let sort = $state(['most','least'].includes(page.url.searchParams.get('sort') ?? '') ? page.url.searchParams.get('sort')! : 'az');
  let results = $state<any[]>([]); let loading = $state(true);
  async function load(){loading=true;const r=await fetch(`/api/directory?kind=${kind}&letter=${letter}&sort=${sort}`);const p=await r.json();results=p.results??[];loading=false;}
  function choose(nextKind:string,nextLetter:string,nextSort=sort){kind=nextKind;letter=nextLetter;sort=nextSort;goto(`/directory?kind=${kind}&letter=${letter}&sort=${sort}`,{replaceState:true,noScroll:true});load();}
  $effect(()=>{load();});
</script>
<svelte:head><title>{kind==='officers'?'Charity officer records':'Charities'} · NZ Records</title></svelte:head>
<header><div><a class="brand" href="/">NZ Records</a><nav><a href="/explore">Search</a><a href="/directory?kind=charities&letter=A">Charities</a><a href="/directory?kind=officers&letter=A">Officer records</a></nav></div></header>
<main><p class="breadcrumb"><a href="/">Home</a> / Public records</p><h1>{kind==='officers'?'Charity officer records':'Charities'}</h1><p class="intro">{kind==='officers'?'People and organisations listed as officers in the Charities Register.':'Charities imported from the New Zealand Charities Register.'}</p>
{#if kind==='officers'}<aside class="note"><strong>A note about names</strong><span>The same person may appear more than once if they are involved with different charities. We don't combine records just because the names match, because they could be different people.</span></aside>{/if}
<div class="tabs"><button class:active={kind==='charities'} onclick={()=>choose('charities',letter)}>Charities</button><button class:active={kind==='officers'} onclick={()=>choose('officers',letter)}>Officer records</button></div>
<nav class="alphabet" aria-label="Browse by first letter">{#each letters as l}<button class:active={letter===l} onclick={()=>choose(kind,l)}>{l}</button>{/each}</nav>
<div class="toolbar"><strong>{loading?'Loading…':`${results.length} records beginning with ${letter}`}</strong><label>Sort by <select value={sort} onchange={(e)=>choose(kind,letter,e.currentTarget.value)}><option value="az">Name A–Z</option><option value="most">Most connections</option><option value="least">Least connections</option></select></label></div>
<section class="results">{#each results as e}<a class="row" href={`/record/${e.id}`}><div><strong>{e.canonical_name}</strong><span>{kind==='officers'?'Charity officer record':e.entity_type.replace('_',' ')}{e.status?` · ${e.status}`:''}{e.nzbn?` · NZBN ${e.nzbn}`:''}</span></div><div class="count"><b>{e.relationship_count??0}</b><span>{Number(e.relationship_count)===1?'connection':'connections'}</span></div><span class="view">View record</span></a>{/each}{#if !loading&&results.length===0}<div class="empty">No imported records beginning with {letter}.</div>{/if}</section>
</main>
<style>:global(*){box-sizing:border-box}:global(body){margin:0;background:#f7f7f4;color:#202624;font-family:Arial,Helvetica,sans-serif}:global(a){color:#135f50}header{background:#fff;border-top:5px solid #176b5a;border-bottom:1px solid #d9ddd9}header>div{max-width:1060px;margin:auto;padding:19px 28px;display:flex;justify-content:space-between;align-items:center}.brand{font-size:22px;font-weight:700;color:#202624;text-decoration:none}header nav{display:flex;gap:24px}header nav a{font-size:14px;font-weight:600}main{max-width:1060px;margin:auto;padding:38px 28px 90px}.breadcrumb{font-size:13px;margin:0 0 28px;color:#69726e}.breadcrumb a{text-decoration:underline}h1{font-family:Georgia,'Times New Roman',serif;font-size:46px;letter-spacing:-.02em;margin:0 0 10px}.intro{font-size:18px;color:#58625e;margin:0 0 25px}.note{max-width:780px;background:#eef4f1;border-left:5px solid #176b5a;padding:17px 20px;margin:25px 0;display:flex;flex-direction:column;gap:6px;line-height:1.5}.note strong{font-size:16px}.note span{color:#46504c}.tabs{display:flex;border-bottom:1px solid #bfc6c1;margin-top:35px}.tabs button{background:none;border:0;border-bottom:4px solid transparent;padding:12px 18px;cursor:pointer;font-size:15px;color:#40504a}.tabs button.active{border-color:#176b5a;color:#202624;font-weight:700}.alphabet{display:flex;flex-wrap:wrap;gap:4px;padding:22px 0}.alphabet button{background:#fff;border:1px solid #bfc6c1;width:34px;height:34px;color:#135f50;font-weight:700;cursor:pointer}.alphabet button:hover,.alphabet button.active{background:#176b5a;color:#fff;border-color:#176b5a}.toolbar{border-top:1px solid #cdd2ce;border-bottom:1px solid #cdd2ce;padding:14px 0;display:flex;justify-content:space-between;align-items:center;gap:20px;font-size:13px}.toolbar label{display:flex;gap:8px;align-items:center}.toolbar select{background:#fff;border:1px solid #909a95;padding:8px;font-size:14px}.results{background:#fff}.row{display:grid;grid-template-columns:1fr 110px 100px;gap:20px;align-items:center;padding:18px 14px;border-bottom:1px solid #d8dcd9;text-decoration:none;color:#202624}.row:hover{background:#f2f5f2}.row>div:first-child{display:flex;flex-direction:column;gap:5px}.row>div:first-child strong{font-size:16px;color:#135f50;text-decoration:underline}.row>div:first-child span{font-size:13px;color:#69736f}.count{display:flex;flex-direction:column;align-items:flex-start}.count b{font-size:17px}.count span{font-size:11px;color:#69736f}.view{font-size:13px;color:#135f50;text-decoration:underline}.empty{padding:35px 14px;color:#68716d}@media(max-width:650px){header>div{align-items:flex-start;flex-direction:column;gap:15px}header nav{flex-wrap:wrap;gap:12px 18px}h1{font-size:38px}.toolbar{align-items:flex-start;flex-direction:column}.row{grid-template-columns:1fr auto}.view{display:none}}</style>